// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user/service.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user/service.proto\x12\x04user\x1a\x13user/messages.proto\x1a\x1bgoogle/protobuf/empty.proto2\xba\x03\n" +
	"\vUserService\x12=\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x18.user.UpdateUserResponse\x12?\n" +
	"\n" +
	"DeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponse\x12<\n" +
	"\tListUsers\x12\x16.user.ListUsersRequest\x1a\x17.user.ListUsersResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12B\n" +
	"\vSetPassword\x12\x18.user.SetPasswordRequest\x1a\x19.user.SetPasswordResponseB/Z-github.com/oj-lab/reborn/protobuf/user;userpbb\x06proto3"

var file_user_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: user.CreateUserRequest
	(*GetUserRequest)(nil),      // 1: user.GetUserRequest
	(*UpdateUserRequest)(nil),   // 2: user.UpdateUserRequest
	(*DeleteUserRequest)(nil),   // 3: user.DeleteUserRequest
	(*ListUsersRequest)(nil),    // 4: user.ListUsersRequest
	(*LoginRequest)(nil),        // 5: user.LoginRequest
	(*SetPasswordRequest)(nil),  // 6: user.SetPasswordRequest
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
	(*GetUserResponse)(nil),     // 8: user.GetUserResponse
	(*UpdateUserResponse)(nil),  // 9: user.UpdateUserResponse
	(*DeleteUserResponse)(nil),  // 10: user.DeleteUserResponse
	(*ListUsersResponse)(nil),   // 11: user.ListUsersResponse
	(*LoginResponse)(nil),       // 12: user.LoginResponse
	(*SetPasswordResponse)(nil), // 13: user.SetPasswordResponse
}
var file_user_service_proto_depIdxs = []int32{
	0,  // 0: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	1,  // 1: user.UserService.GetUser:input_type -> user.GetUserRequest
	2,  // 2: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	3,  // 3: user.UserService.DeleteUser:input_type -> user.DeleteUserRequest
	4,  // 4: user.UserService.ListUsers:input_type -> user.ListUsersRequest
	5,  // 5: user.UserService.Login:input_type -> user.LoginRequest
	6,  // 6: user.UserService.SetPassword:input_type -> user.SetPasswordRequest
	7,  // 7: user.UserService.CreateUser:output_type -> google.protobuf.Empty
	8,  // 8: user.UserService.GetUser:output_type -> user.GetUserResponse
	9,  // 9: user.UserService.UpdateUser:output_type -> user.UpdateUserResponse
	10, // 10: user.UserService.DeleteUser:output_type -> user.DeleteUserResponse
	11, // 11: user.UserService.ListUsers:output_type -> user.ListUsersResponse
	12, // 12: user.UserService.Login:output_type -> user.LoginResponse
	13, // 13: user.UserService.SetPassword:output_type -> user.SetPasswordResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	file_user_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
