[server]
port = 50051


[jwt]
secret = "DtVrEsDBH7kkZL1AjLpXHDvDT7RAkHWbGOO1jPS13rU="
issuer = "oj-lab-api"
expires_in_hours = 72

[auth]
public_methods = [
    "/user.UserService/Login",
    "/user.UserService/OAuthLogin",
    "/user.UserService/CreateUser"
]

[auth.acl]
"/user.UserService/DeleteUser" = ["ADMIN"]
"/user.UserService/ListUsers" = ["ADMIN"]

[gorm_client.database]
driver = "postgres"
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
name = "postgres"
sslmode = "disable"
